# Generated by Django 4.2.5 on 2023-09-28 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodstuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Продукт')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('weight', models.FloatField(default=0.1, verbose_name='Вес в кг')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('Classic', 'Classic'), ('Low Сarb', 'Low Сarb'), ('Vegetarian', 'Vegetarian'), ('Keto', 'Keto')], default='Classic', max_length=10, verbose_name='Тип меню')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления, мин.')),
                ('calories', models.IntegerField(verbose_name='Калорий на 100г.')),
                ('fats', models.IntegerField(verbose_name='Жиров на 100г.')),
                ('proteins', models.IntegerField(verbose_name='Белков на 100г.')),
                ('carbs', models.IntegerField(verbose_name='Углеводов на 100г.')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('Classic', 'Classic'), ('Low Сarb', 'Low Сarb'), ('Vegetarian', 'Vegetarian'), ('Keto', 'Keto')], default='Classic', max_length=10, verbose_name='Тип меню')),
                ('number_persons', models.IntegerField(default=1, verbose_name='Количество персон')),
                ('calories', models.CharField(choices=[('1000', 'Basic'), ('1400', 'Fit'), ('1800', 'Balance')], default='1800', max_length=7, verbose_name='Калорий в день')),
                ('number_of_meals', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4')], default='3', max_length=1, verbose_name='Приемов пищи в день')),
                ('allergies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_plan.foodstuff', verbose_name='Продукты, на которые естьалергия')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('image_position', models.IntegerField(default=0, verbose_name='Позиция картинки')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='food_plan.recipe')),
            ],
            options={
                'ordering': ['image_position'],
            },
        ),
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.1, verbose_name='Вес в кг')),
                ('food_name', models.ManyToManyField(to='food_plan.foodstuff', verbose_name='Продукт')),
                ('recipe', models.ManyToManyField(related_name='food_lists', to='food_plan.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тип блюда')),
                ('recipe', models.ManyToManyField(related_name='dish_types', to='food_plan.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Инструкция рецепта')),
                ('text_position', models.IntegerField(default=0, verbose_name='Позиция текста')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='food_plan.recipe')),
            ],
            options={
                'ordering': ['text_position'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(choices=[('R', 'Regular'), ('P', 'Premium')], default='R', max_length=7, verbose_name='Подписка')),
                ('subscription_expiration_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата окончания подписки')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_plan.mealplan', verbose_name='План питания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
