# Generated by Django 4.2.5 on 2023-09-30 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('subscription', models.CharField(choices=[('R', 'Regular'), ('P', 'Premium')], default='R', max_length=7, verbose_name='Подписка')),
                ('subscription_expiration_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата окончания подписки')),
                ('free_recipes', models.IntegerField(default=3, verbose_name='Доступно бесплатных рецептов')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Foodstuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Продукт')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('weight', models.FloatField(default=0.1, verbose_name='Вес в кг')),
            ],
            options={
                'verbose_name': 'Все продукты',
                'verbose_name_plural': 'Все продукты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название рецепта')),
                ('menu_type', models.CharField(choices=[('Classic', 'Classic'), ('Low Сarb', 'Low Сarb'), ('Vegetarian', 'Vegetarian'), ('Keto', 'Keto')], default='Classic', max_length=10, verbose_name='Тип меню')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления, мин.')),
                ('calories', models.IntegerField(verbose_name='Калорий на 100г.')),
                ('fats', models.IntegerField(verbose_name='Жиров на 100г.')),
                ('proteins', models.IntegerField(verbose_name='Белков на 100г.')),
                ('carbs', models.IntegerField(verbose_name='Углеводов на 100г.')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Инструкция рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('Classic', 'Classic'), ('Low Сarb', 'Low Сarb'), ('Vegetarian', 'Vegetarian'), ('Keto', 'Keto')], default='Classic', max_length=10, verbose_name='Тип меню')),
                ('number_persons', models.IntegerField(default=1, verbose_name='Количество персон')),
                ('calories', models.CharField(choices=[('1000', 'Basic'), ('1400', 'Fit'), ('1800', 'Balance')], default='1800', max_length=7, verbose_name='Калорий в день')),
                ('number_of_meals', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4')], default='3', max_length=1, verbose_name='Приемов пищи в день')),
                ('allergies', models.ManyToManyField(blank=True, default=None, related_name='meal_plans', to='food_plan.foodstuff', verbose_name='Продукты, на которые есть алергия')),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to='food_plan.client', verbose_name='Клиент')),
                ('recipes', models.ManyToManyField(related_name='meal_plans', to='food_plan.recipe', verbose_name='Рецепты')),
            ],
            options={
                'verbose_name': 'План питания',
                'verbose_name_plural': 'Планы питания',
            },
        ),
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.1, verbose_name='Вес в кг')),
                ('food_names', models.ManyToManyField(related_name='food_lists', to='food_plan.foodstuff', verbose_name='Продукты')),
                ('recipes', models.ManyToManyField(related_name='food_lists', to='food_plan.recipe')),
            ],
            options={
                'verbose_name': 'Список продуктов',
                'verbose_name_plural': 'Списки продуктов',
            },
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тип блюда')),
                ('recipes', models.ManyToManyField(related_name='dish_types', to='food_plan.recipe')),
            ],
            options={
                'verbose_name': 'Разновидность бюда',
                'verbose_name_plural': 'Разновидности блюд',
            },
        ),
    ]
