# Generated by Django 4.2.5 on 2023-09-29 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RenameField(
            model_name='dishtype',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.RenameField(
            model_name='foodlist',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.RemoveField(
            model_name='foodlist',
            name='food_name',
        ),
        migrations.AddField(
            model_name='foodlist',
            name='food_names',
            field=models.ManyToManyField(related_name='food_lists', to='food_plan.foodstuff', verbose_name='Продукты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_plans',
            field=models.ManyToManyField(related_name='recipes', to='food_plan.mealplan', verbose_name='Планы питания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='food_plan.mealplan', verbose_name='План питания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='allergies',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='allergies',
            field=models.ManyToManyField(related_name='meal_plans', to='food_plan.foodstuff', verbose_name='Продукты, на которые есть алергия'),
        ),
    ]
