# Generated by Django 4.0 on 2023-10-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=40, null=True, verbose_name='статус оплаты'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=40, null=True, verbose_name='id транзакции'),
        ),
    ]
