# Generated by Django 4.0 on 2023-10-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='meal_plans', to='food_plan.Recipe', verbose_name='Рецепты'),
        ),
    ]
