# Generated by Django 4.2.5 on 2023-09-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0002_alter_client_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['text_position'], 'verbose_name': 'Описание рецепта', 'verbose_name_plural': 'Описания рецептов'},
        ),
        migrations.AlterModelOptions(
            name='dishtype',
            options={'verbose_name': 'Разновидность бюда', 'verbose_name_plural': 'Раздновидности блюд'},
        ),
        migrations.AlterModelOptions(
            name='foodlist',
            options={'verbose_name': 'Список продуктов', 'verbose_name_plural': 'Списки продуктов'},
        ),
        migrations.AlterModelOptions(
            name='foodstuff',
            options={'verbose_name': 'Все продукты', 'verbose_name_plural': 'Все продукты'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_position'], 'verbose_name': 'Картинка рецепта', 'verbose_name_plural': 'Картинки рецептов'},
        ),
        migrations.AlterModelOptions(
            name='mealplan',
            options={'verbose_name': 'План питания', 'verbose_name_plural': 'Планы питания'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='meal_plan',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to='food_plan.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='allergies',
            field=models.ManyToManyField(blank=True, default=None, related_name='meal_plans', to='food_plan.foodstuff', verbose_name='Продукты, на которые есть алергия'),
        ),
    ]
