# Generated by Django 4.0 on 2023-10-01 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0002_transaction_price_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_name',
            field=models.CharField(choices=[('1', '1 мес.'), ('3', '3 мес.'), ('6', '6 мес.'), ('12', '12 мес.')], max_length=8, verbose_name='Название подписки'),
        ),
    ]
