# Generated by Django 4.0 on 2023-10-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0002_alter_mealplan_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тип блюда'),
        ),
    ]
