# Generated by Django 4.2.5 on 2023-09-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0003_alter_description_options_alter_dishtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishtype',
            options={'verbose_name': 'Разновидность бюда', 'verbose_name_plural': 'Разновидности блюд'},
        ),
    ]
