# Generated by Django 4.0 on 2023-09-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0004_alter_dishtype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishtype',
            name='recipes',
            field=models.ManyToManyField(related_name='dish_types', to='food_plan.Recipe'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='food_names',
            field=models.ManyToManyField(related_name='food_lists', to='food_plan.Foodstuff', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='recipes',
            field=models.ManyToManyField(related_name='food_lists', to='food_plan.Recipe'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='allergies',
            field=models.ManyToManyField(blank=True, default=None, related_name='meal_plans', to='food_plan.Foodstuff', verbose_name='Продукты, на которые есть алергия'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_plans',
            field=models.ManyToManyField(related_name='recipes', to='food_plan.MealPlan', verbose_name='Планы питания'),
        ),
    ]
