# Generated by Django 4.2.5 on 2023-09-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0006_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='free_recipes',
            field=models.IntegerField(default=3, verbose_name='Доступно бесплатных рецептов'),
        ),
    ]
